
// Generated by ntoolkit/futures
package futures_test

import "ntoolkit/futures"


type DeferredValueInt struct {
	DeferredValue futures.Promise
}

func (promise *DeferredValueInt) init() {
	if promise.DeferredValue == nil {
		promise.DeferredValue = &futures.DeferredValue{}
	}
}

func (promise *DeferredValueInt) Resolve(result int) {
	promise.init()
	promise.DeferredValue.PResolve(result)
}

func (promise *DeferredValueInt) Reject(err error) {
	promise.init()
	promise.DeferredValue.PReject(err)
}

func (promise *DeferredValueInt) Errors() []error {
	promise.init()
	return promise.DeferredValue.PErrors()
}

func (promise *DeferredValueInt) Then(resolve func(int), reject func(error)) *DeferredValueInt {
	promise.init()
	promise.DeferredValue.PThen(func(value interface{}) {
		if v, ok := value.(int); ok {
			resolve(v)
		}
		panic("Invalid value used to resolve DeferredValueInt")
	}, reject)
	return promise
}

func (promise *DeferredValueInt) PThen(result func(interface{}), reject func(error)) futures.Promise {
	promise.init()
	return promise.DeferredValue.PThen(result, reject)
}

func (promise *DeferredValueInt) PErrors() []error {
	promise.init()
	return promise.DeferredValue.PErrors()
}

func (promise *DeferredValueInt) PResolve(result interface{}) {
	promise.init()
	promise.DeferredValue.PResolve(result)
}

func (promise *DeferredValueInt) PReject(err error) {
	promise.init()
	promise.DeferredValue.PReject(err)
}
